name: shell command

on: 
  - push 

jobs: 
  run-shell-command: 
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "hellow world"
      - name: multi_line script
        run: |
          node -v
          npm -v